services:
  - type: web
    name: medimate
    env: docker
    rootDir: backend
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
